"""initial application metadata

Revision ID: 49a011c37db2
Revises:
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "49a011c37db2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
    )
    op.create_table(
        "evaluation_suites",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_suites")),
    )
    op.create_table(
        "execution_targets",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("credential_ref", sa.String(), nullable=True),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credential_ref IS NULL OR credential_ref ~ '^[a-z][a-z0-9+.-]*://.+$'",
            name=op.f("ck_execution_targets_credential_reference"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_targets")),
        sa.UniqueConstraint("name", name=op.f("uq_execution_targets_name")),
    )
    op.create_table(
        "llm_providers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("api_key_ref", sa.String(), nullable=True),
        sa.Column(
            "model_names",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "api_key_ref IS NULL OR api_key_ref ~ '^[a-z][a-z0-9+.-]*://.+$'",
            name=op.f("ck_llm_providers_credential_reference"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_providers")),
        sa.UniqueConstraint("name", name=op.f("uq_llm_providers_name")),
    )
    op.create_table(
        "model_catalog_entries",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("repository", sa.String(), nullable=False),
        sa.Column("revision", sa.String(), nullable=False),
        sa.Column("license", sa.String(), nullable=False),
        sa.Column("gated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_catalog_entries")),
        sa.UniqueConstraint("key", name=op.f("uq_model_catalog_entries_key")),
    )
    op.create_table(
        "models",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
    )
    op.create_table(
        "evaluation_prompts",
        sa.Column("suite_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_evaluation_prompts_nonnegative_position")
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["evaluation_suites.id"],
            name=op.f("fk_evaluation_prompts_suite_id_evaluation_suites"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_prompts")),
        sa.UniqueConstraint("suite_id", "position", name=op.f("uq_evaluation_prompts_suite_id")),
    )
    op.create_index(
        op.f("ix_evaluation_prompts_suite_id"), "evaluation_prompts", ["suite_id"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_model_versions_positive_version")),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_model_versions_model_id_models")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("model_id", "version", name=op.f("uq_model_versions_model_id")),
    )
    op.create_index(
        op.f("ix_model_versions_model_id"), "model_versions", ["model_id"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("model_version_id", sa.Uuid(), nullable=True),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_artifacts_valid_sha256")),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_artifacts_nonnegative_size")),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_artifacts_model_version_id_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("bucket", "object_key", name=op.f("uq_artifacts_bucket")),
    )
    op.create_index(
        op.f("ix_artifacts_model_version_id"), "artifacts", ["model_version_id"], unique=False
    )
    op.create_table(
        "model_version_parents",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "child_id <> parent_id", name=op.f("ck_model_version_parents_no_self_parent")
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["model_versions.id"],
            name=op.f("fk_model_version_parents_child_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["model_versions.id"],
            name=op.f("fk_model_version_parents_parent_id_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_version_parents")),
        sa.UniqueConstraint(
            "child_id", "parent_id", name=op.f("uq_model_version_parents_child_id")
        ),
    )
    op.create_index(
        op.f("ix_model_version_parents_child_id"),
        "model_version_parents",
        ["child_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_version_parents_parent_id"),
        "model_version_parents",
        ["parent_id"],
        unique=False,
    )
    op.create_table(
        "artifact_derivations",
        sa.Column("child_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "child_id <> parent_id", name=op.f("ck_artifact_derivations_no_self_parent")
        ),
        sa.ForeignKeyConstraint(
            ["child_id"], ["artifacts.id"], name=op.f("fk_artifact_derivations_child_id_artifacts")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["artifacts.id"],
            name=op.f("fk_artifact_derivations_parent_id_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_derivations")),
        sa.UniqueConstraint("child_id", "parent_id", name=op.f("uq_artifact_derivations_child_id")),
    )
    op.create_index(
        op.f("ix_artifact_derivations_child_id"), "artifact_derivations", ["child_id"], unique=False
    )
    op.create_index(
        op.f("ix_artifact_derivations_parent_id"),
        "artifact_derivations",
        ["parent_id"],
        unique=False,
    )
    op.create_table(
        "dataset_sources",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifacts.id"], name=op.f("fk_dataset_sources_artifact_id_artifacts")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_dataset_sources_dataset_id_datasets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_sources")),
    )
    op.create_index(
        op.f("ix_dataset_sources_artifact_id"), "dataset_sources", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_sources_dataset_id"), "dataset_sources", ["dataset_id"], unique=False
    )
    op.create_table(
        "dataset_versions",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("manifest_version", sa.String(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(manifest) = 'object'", name=op.f("ck_dataset_versions_manifest_object")
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_dataset_versions_valid_sha256")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_dataset_versions_positive_version")),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_dataset_versions_dataset_id_datasets")
        ),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_dataset_versions_manifest_artifact_id_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint("dataset_id", "version", name=op.f("uq_dataset_versions_dataset_id")),
    )
    op.create_index(
        op.f("ix_dataset_versions_dataset_id"), "dataset_versions", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_versions_manifest_artifact_id"),
        "dataset_versions",
        ["manifest_artifact_id"],
        unique=False,
    )
    op.create_table(
        "deployments",
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("execution_target_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), server_default="QUEUED", nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("endpoint", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifacts.id"], name=op.f("fk_deployments_artifact_id_artifacts")
        ),
        sa.ForeignKeyConstraint(
            ["execution_target_id"],
            ["execution_targets.id"],
            name=op.f("fk_deployments_execution_target_id_execution_targets"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_deployments_model_version_id_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
    )
    op.create_index(
        op.f("ix_deployments_artifact_id"), "deployments", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_deployments_execution_target_id"),
        "deployments",
        ["execution_target_id"],
        unique=False,
    )
    op.create_index(op.f("ix_deployments_expires_at"), "deployments", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_deployments_model_version_id"), "deployments", ["model_version_id"], unique=False
    )
    op.create_index(op.f("ix_deployments_status"), "deployments", ["status"], unique=False)
    op.create_table(
        "model_sources",
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_entry_id", sa.Uuid(), nullable=True),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("revision", sa.String(), nullable=True),
        sa.Column("license", sa.String(), nullable=False),
        sa.Column("license_url", sa.String(), nullable=True),
        sa.Column("gated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifacts.id"], name=op.f("fk_model_sources_artifact_id_artifacts")
        ),
        sa.ForeignKeyConstraint(
            ["catalog_entry_id"],
            ["model_catalog_entries.id"],
            name=op.f("fk_model_sources_catalog_entry_id_model_catalog_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_model_sources_model_version_id_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_sources")),
    )
    op.create_index(
        op.f("ix_model_sources_artifact_id"), "model_sources", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_sources_catalog_entry_id"),
        "model_sources",
        ["catalog_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_sources_model_version_id"),
        "model_sources",
        ["model_version_id"],
        unique=False,
    )
    op.create_table(
        "conversation_imports",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("importer", sa.String(), nullable=False),
        sa.Column("importer_version", sa.String(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_conversation_imports_canonical_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["dataset_sources.id"],
            name=op.f("fk_conversation_imports_source_id_dataset_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_imports")),
    )
    op.create_index(
        op.f("ix_conversation_imports_canonical_artifact_id"),
        "conversation_imports",
        ["canonical_artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_imports_source_id"),
        "conversation_imports",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_documents_canonical_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["dataset_sources.id"],
            name=op.f("fk_documents_source_id_dataset_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_canonical_artifact_id"),
        "documents",
        ["canonical_artifact_id"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_source_id"), "documents", ["source_id"], unique=False)
    op.create_table(
        "training_runs",
        sa.Column("base_model_version_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("execution_target_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_suite_id", sa.Uuid(), nullable=True),
        sa.Column("appspec_version", sa.String(), nullable=False),
        sa.Column("appspec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(), server_default="QUEUED", nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(appspec) = 'object'", name=op.f("ck_training_runs_appspec_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(resolved_config) = 'object'",
            name=op.f("ck_training_runs_resolved_object"),
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_training_runs_valid_sha256")),
        sa.ForeignKeyConstraint(
            ["base_model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_training_runs_base_model_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_training_runs_dataset_version_id_dataset_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_suite_id"],
            ["evaluation_suites.id"],
            name=op.f("fk_training_runs_evaluation_suite_id_evaluation_suites"),
        ),
        sa.ForeignKeyConstraint(
            ["execution_target_id"],
            ["execution_targets.id"],
            name=op.f("fk_training_runs_execution_target_id_execution_targets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_runs")),
    )
    op.create_index(
        op.f("ix_training_runs_base_model_version_id"),
        "training_runs",
        ["base_model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_runs_dataset_version_id"),
        "training_runs",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_runs_evaluation_suite_id"),
        "training_runs",
        ["evaluation_suite_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_runs_execution_target_id"),
        "training_runs",
        ["execution_target_id"],
        unique=False,
    )
    op.create_index(op.f("ix_training_runs_status"), "training_runs", ["status"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("source_conversation_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "message_count >= 0", name=op.f("ck_conversations_nonnegative_messages")
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["conversation_imports.id"],
            name=op.f("fk_conversations_import_id_conversation_imports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "import_id", "source_conversation_id", name=op.f("uq_conversations_import_id")
        ),
    )
    op.create_index(
        op.f("ix_conversations_import_id"), "conversations", ["import_id"], unique=False
    )
    op.create_table(
        "evaluation_results",
        sa.Column("training_run_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_id", sa.Uuid(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("response_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("preference", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_evaluation_results_model_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["evaluation_prompts.id"],
            name=op.f("fk_evaluation_results_prompt_id_evaluation_prompts"),
        ),
        sa.ForeignKeyConstraint(
            ["response_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_evaluation_results_response_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["training_run_id"],
            ["training_runs.id"],
            name=op.f("fk_evaluation_results_training_run_id_training_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_results")),
    )
    op.create_index(
        op.f("ix_evaluation_results_model_version_id"),
        "evaluation_results",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_results_prompt_id"), "evaluation_results", ["prompt_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_results_response_artifact_id"),
        "evaluation_results",
        ["response_artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_results_training_run_id"),
        "evaluation_results",
        ["training_run_id"],
        unique=False,
    )
    op.create_table(
        "job_events",
        sa.Column("training_run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sequence >= 0", name=op.f("ck_job_events_nonnegative_sequence")),
        sa.ForeignKeyConstraint(
            ["training_run_id"],
            ["training_runs.id"],
            name=op.f("fk_job_events_training_run_id_training_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint(
            "training_run_id", "sequence", name=op.f("uq_job_events_training_run_id")
        ),
    )
    op.create_index(
        op.f("ix_job_events_training_run_id"), "job_events", ["training_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_events_training_run_id"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_evaluation_results_training_run_id"), table_name="evaluation_results")
    op.drop_index(
        op.f("ix_evaluation_results_response_artifact_id"), table_name="evaluation_results"
    )
    op.drop_index(op.f("ix_evaluation_results_prompt_id"), table_name="evaluation_results")
    op.drop_index(op.f("ix_evaluation_results_model_version_id"), table_name="evaluation_results")
    op.drop_table("evaluation_results")
    op.drop_index(op.f("ix_conversations_import_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_training_runs_status"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_execution_target_id"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_evaluation_suite_id"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_dataset_version_id"), table_name="training_runs")
    op.drop_index(op.f("ix_training_runs_base_model_version_id"), table_name="training_runs")
    op.drop_table("training_runs")
    op.drop_index(op.f("ix_documents_source_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_canonical_artifact_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_conversation_imports_source_id"), table_name="conversation_imports")
    op.drop_index(
        op.f("ix_conversation_imports_canonical_artifact_id"), table_name="conversation_imports"
    )
    op.drop_table("conversation_imports")
    op.drop_index(op.f("ix_model_sources_model_version_id"), table_name="model_sources")
    op.drop_index(op.f("ix_model_sources_catalog_entry_id"), table_name="model_sources")
    op.drop_index(op.f("ix_model_sources_artifact_id"), table_name="model_sources")
    op.drop_table("model_sources")
    op.drop_index(op.f("ix_deployments_status"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_model_version_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_expires_at"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_execution_target_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_artifact_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_dataset_versions_manifest_artifact_id"), table_name="dataset_versions")
    op.drop_index(op.f("ix_dataset_versions_dataset_id"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index(op.f("ix_dataset_sources_dataset_id"), table_name="dataset_sources")
    op.drop_index(op.f("ix_dataset_sources_artifact_id"), table_name="dataset_sources")
    op.drop_table("dataset_sources")
    op.drop_index(op.f("ix_artifact_derivations_parent_id"), table_name="artifact_derivations")
    op.drop_index(op.f("ix_artifact_derivations_child_id"), table_name="artifact_derivations")
    op.drop_table("artifact_derivations")
    op.drop_index(op.f("ix_model_version_parents_parent_id"), table_name="model_version_parents")
    op.drop_index(op.f("ix_model_version_parents_child_id"), table_name="model_version_parents")
    op.drop_table("model_version_parents")
    op.drop_index(op.f("ix_artifacts_model_version_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_model_versions_model_id"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_evaluation_prompts_suite_id"), table_name="evaluation_prompts")
    op.drop_table("evaluation_prompts")
    op.drop_table("models")
    op.drop_table("model_catalog_entries")
    op.drop_table("llm_providers")
    op.drop_table("execution_targets")
    op.drop_table("evaluation_suites")
    op.drop_table("datasets")
    # ### end Alembic commands ###
