"""artifact upload reservations

Revision ID: 876f49074a6f
Revises: 0002_metadata_guards
"""

import sqlalchemy as sa

from alembic import op

revision = "876f49074a6f"
down_revision = "0002_metadata_guards"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact_uploads",
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_artifact_uploads_nonnegative_size")),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_artifact_uploads_artifact_id_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_uploads")),
        sa.UniqueConstraint("artifact_id", name=op.f("uq_artifact_uploads_artifact_id")),
        sa.UniqueConstraint("object_key", name=op.f("uq_artifact_uploads_object_key")),
    )
    op.create_index(
        op.f("ix_artifact_uploads_expires_at"), "artifact_uploads", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifact_uploads_expires_at"), table_name="artifact_uploads")
    op.drop_table("artifact_uploads")
    # ### end Alembic commands ###
