"""conversation selection and import warnings

Revision ID: 953d3fcf27d6
Revises: 0004_upload_identity_guard
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "953d3fcf27d6"
down_revision = "0004_upload_identity_guard"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("selected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "warnings")
    op.drop_column("conversations", "selected")
    # ### end Alembic commands ###
