"""document ingestion provenance

Revision ID: df16af97c9ad
Revises: 953d3fcf27d6
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "df16af97c9ad"
down_revision = "953d3fcf27d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_ingestions",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("output_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("logs_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed')", name=op.f("ck_document_ingestions_valid_status")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_document_ingestions_positive_version")),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_document_ingestions_dataset_id_datasets")
        ),
        sa.ForeignKeyConstraint(
            ["logs_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_document_ingestions_logs_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_document_ingestions_manifest_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["output_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_document_ingestions_output_artifact_id_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_ingestions")),
        sa.UniqueConstraint(
            "dataset_id", "version", name=op.f("uq_document_ingestions_dataset_id")
        ),
    )
    op.create_index(
        op.f("ix_document_ingestions_dataset_id"),
        "document_ingestions",
        ["dataset_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_ingestions_dataset_id"), table_name="document_ingestions")
    op.drop_table("document_ingestions")
    # ### end Alembic commands ###
