"""add immutable training plans

Revision ID: f6263d0b8ecb
Revises: 0007_document_ingestion_guards
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "f6263d0b8ecb"
down_revision = "0007_document_ingestion_guards"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_plans",
        sa.Column("base_model_version_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("appspec_version", sa.String(), nullable=False),
        sa.Column("appspec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_training_plans_valid_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["base_model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_training_plans_base_model_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
            name=op.f("fk_training_plans_dataset_version_id_dataset_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_plans")),
    )
    op.create_index(
        op.f("ix_training_plans_base_model_version_id"),
        "training_plans",
        ["base_model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_plans_dataset_version_id"),
        "training_plans",
        ["dataset_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_training_plans_dataset_version_id"), table_name="training_plans")
    op.drop_index(op.f("ix_training_plans_base_model_version_id"), table_name="training_plans")
    op.drop_table("training_plans")
    # ### end Alembic commands ###
