"""Resolve the light Soup image dependencies using its pinned Python base."""

import subprocess
from pathlib import Path

root = Path(__file__).resolve().parents[1]
base = (root / "images/soup-ingest/Dockerfile").read_text().splitlines()[0].split()[1]
resolved = subprocess.check_output(
    [
        "docker",
        "run",
        "--rm",
        "--volume",
        str(root / "images/soup-ingest/requirements.in") + ":/requirements.in:ro",
        base,
        "sh",
        "-c",
        "pip install --no-cache-dir -r /requirements.in >&2 && pip freeze",
    ],
    text=True,
)
(root / "images/soup-ingest/requirements.txt").write_text(
    "# Generated by scripts/lock_soup_ingest.py; edit requirements.in.\n" + resolved
)
